const serviceCardData = [
  // {
  //   title: "Fabrication & Installation",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971584/fast_response_service/ys3ioq8768coqwi63qjl.png",
  //   price: 34,
  //   serviceType: "Fabrication",
  //   category: "Fabrication",
  //   specialization: ["fabricator", "welder"],
  //   tags: ["fabrication", "welding", "metal work", "installation", "industrial"],
  //   rating: 0,
  //   isMostBooked: false,
  //   isTopCategory: false,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },
  // {
  //   title: "Shutter Making, Installation & Service",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971580/fast_response_service/tee2ciatiqmacf2btxfh.png",
  //   price: 45,
  //   serviceType: "Shutter Work",
  //   category: "Construction",
  //   specialization: ["fabricator", "mechanic"],
  //   tags: ["shutter", "rolling shutter", "industrial shutter", "installation", "repair"],
  //   rating: 0,
  //   isMostBooked: false,
  //   isTopCategory: false,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },
  // {
  //   title: "M.S Fabrication & Grill Gate Fabrication",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/ljtjld56ikcpltbb1ylp.png",
  //   price: 55,
  //   serviceType: "Metal Fabrication",
  //   category: "Fabrication",
  //   specialization: ["fabricator", "welder"],
  //   tags: ["ms fabrication", "gate fabrication", "grill", "steel work", "custom metal"],
  //   rating: 0,
  //   isMostBooked: false,
  //   isTopCategory: false,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },
  // {
  //   title: "Tin Shade / Factory Shade Installation",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971585/fast_response_service/wxb7bcvt3zb8czegt0tk.png",
  //   price: 25,
  //   serviceType: "Shade Installation",
  //   category: "Construction",
  //   specialization: ["fabricator", "construction"],
  //   tags: ["tin shed", "factory shed", "shade installation", "warehouse", "roof work"],
  //   rating: 0,
  //   isMostBooked: false,
  //   isTopCategory: false,
  //   isNewLaunched: true,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },
  // {
  //   title: "Aluminium Door, Window & Cabin Installation",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971580/fast_response_service/vh8roo1rho5og72rz3uz.png",
  //   price: 40,
  //   serviceType: "Aluminium Work",
  //   category: "Fabrication",
  //   specialization: ["aluminium technician", "fabricator"],
  //   tags: ["aluminium door", "aluminium window", "office cabin", "partition"],
  //   rating: 0,
  //   isMostBooked: true,
  //   isTopCategory: false,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },
  // {
  //   title: "SS Welding Work",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971581/fast_response_service/bf3yknopx1qbdxis2uz1.png",
  //   price: 38,
  //   serviceType: "Welding",
  //   category: "Fabrication",
  //   specialization: ["welder"],
  //   tags: ["ss welding", "stainless steel", "welding work", "metal join"],
  //   rating: 0,
  //   isMostBooked: true,
  //   isTopCategory: false,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "Racks & Shelves Installation Work",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971581/fast_response_service/ppufns8a15uuporvwot8.png",
  //   price: 30,
  //   serviceType: "Installation",
  //   category: "Carpentry",
  //   specialization: ["carpenter"],
  //   tags: ["storage rack", "shelves", "shop rack", "warehouse rack"],
  //   rating: 0,
  //   isMostBooked: false,
  //   isTopCategory: false,
  //   isNewLaunched: true,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "Interior & Furniture",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/ulzn3bj2jwkts2wempaf.png",
  //   price: 60,
  //   serviceType: "Interior Work",
  //   category: "Interior",
  //   specialization: ["interior designer", "carpenter"],
  //   tags: ["interior design", "furniture", "home interior", "office interior"],
  //   rating: 0,
  //   isMostBooked: true,
  //   isTopCategory: true,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "Modular Kitchen Work",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971583/fast_response_service/h2rzullwj2rycnsasjay.png",
  //   price: 50,
  //   serviceType: "Kitchen Work",
  //   category: "Interior",
  //   specialization: ["interior designer", "carpenter"],
  //   tags: ["modular kitchen", "kitchen interior", "cabinet work"],
  //   rating: 0,
  //   isMostBooked: true,
  //   isTopCategory: true,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "Furniture Work",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971581/fast_response_service/a2smwevd4ntpksl6jn7u.png",
  //   price: 28,
  //   serviceType: "Carpentry",
  //   category: "Carpentry",
  //   specialization: ["carpenter"],
  //   tags: ["furniture repair", "custom furniture", "wood work"],
  //   rating: 0,
  //   isMostBooked: false,
  //   isTopCategory: false,
  //   isNewLaunched: true,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "Plumbing Services",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971581/fast_response_service/kyf7ngww3damdxxbkwmk.png",
  //   price: 15,
  //   serviceType: "Plumbing",
  //   category: "Plumbing",
  //   specialization: ["plumber"],
  //   tags: ["plumbing", "pipe repair", "leakage", "bathroom fitting"],
  //   rating: 0,
  //   isMostBooked: true,
  //   isTopCategory: false,
  //   isNewLaunched: true,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "Electrical & Mechanical Services",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971581/fast_response_service/lgdhri5vijwtr46jtguf.png",
  //   price: 15,
  //   serviceType: "Electrical",
  //   category: "Electrical",
  //   specialization: ["electrician", "mechanic"],
  //   tags: ["electrical", "mechanical", "machine repair", "industrial electrical"],
  //   rating: 0,
  //   isMostBooked: true,
  //   isTopCategory: true,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "AC Installation & Services",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/ipyb2btfxrrnfi3gv8z3.png",
  //   price: 15,
  //   serviceType: "AC Repair",
  //   category: "HVAC",
  //   specialization: ["actechnician", "hvac"],
  //   tags: ["ac installation", "ac repair", "cooling", "hvac service"],
  //   rating: 0,
  //   isMostBooked: true,
  //   isTopCategory: false,
  //   isNewLaunched: true,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "HVAC Work",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/iaxb7ladmbn9ae8opoqx.png",
  //   price: 15,
  //   serviceType: "HVAC",
  //   category: "HVAC",
  //   specialization: ["hvac"],
  //   tags: ["hvac", "ventilation", "air conditioning", "industrial hvac"],
  //   rating: 0,
  //   isMostBooked: false,
  //   isTopCategory: true,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "CCTV Security Services",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971581/fast_response_service/ndzrrdot6dem3ppfk0s9.png",
  //   price: 15,
  //   serviceType: "Security",
  //   category: "Security",
  //   specialization: ["cctv technician"],
  //   tags: ["cctv", "security camera", "surveillance", "installation"],
  //   rating: 0,
  //   isMostBooked: true,
  //   isTopCategory: false,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "Solar Plant Installation & Maintenance",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/mealsp4lvzznmqxoxbnv.png",
  //   price: 15,
  //   serviceType: "Solar",
  //   category: "Electrical",
  //   specialization: ["solar technician", "electrician"],
  //   tags: ["solar panel", "solar plant", "renewable energy", "maintenance"],
  //   rating: 0,
  //   isMostBooked: true,
  //   isTopCategory: true,
  //   isNewLaunched: false,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "Automobile Services",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971581/fast_response_service/ojtam16zmuadggq4zxnj.png",
  //   price: 15,
  //   serviceType: "Auto Repair",
  //   category: "Automobile",
  //   specialization: ["mechanic"],
  //   tags: ["automobile", "vehicle repair", "car service", "mechanic"],
  //   rating: 0,
  //   isMostBooked: false,
  //   isTopCategory: false,
  //   isNewLaunched: true,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // },

  // {
  //   title: "Body Maker",
  //   cardIcon: "https://res.cloudinary.com/athratech/image/upload/v1763971587/fast_response_service/i1wkzyghqf7fe2ttgg9c.png",
  //   price: 15,
  //   serviceType: "Automobile Fabrication",
  //   category: "Automobile",
  //   specialization: ["body maker"],
  //   tags: ["vehicle body", "truck body", "fabrication", "custom body"],
  //   rating: 0,
  //   isMostBooked: true,
  //   isTopCategory: false,
  //   isNewLaunched: true,
  //   isActive: true,
  //   createdAt: new Date(),
  //   updatedAt: new Date(),
  // }
  
  {
    "title": "Solar Plant Installation & Maintenance",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar0.png",
    "price": 15,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar technician", "electrician"],
    "tags": ["solar panel", "solar plant", "renewable energy", "maintenance"],
    "rating": 0,
    "isMostBooked": true,
    "isTopCategory": true,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Residential Rooftop Solar Installation",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar1.png",
    "price": 12,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar technician"],
    "tags": ["rooftop solar", "home solar"],
    "rating": 0,
    "isMostBooked": true,
    "isTopCategory": true,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Commercial Solar Power Plant Setup",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar2.png",
    "price": 30,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar engineer"],
    "tags": ["commercial solar", "solar plant"],
    "rating": 0,
    "isMostBooked": true,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar Panel Cleaning",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar3.png",
    "price": 5,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar technician"],
    "tags": ["panel cleaning", "efficiency"],
    "rating": 0,
    "isMostBooked": true,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar Inverter Installation",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar4.png",
    "price": 8,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["electrician", "solar technician"],
    "tags": ["solar inverter", "backup"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": true,
    "isActive": true
  },
  {
    "title": "Solar Battery Installation",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar5.png",
    "price": 10,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar technician"],
    "tags": ["solar battery", "storage"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": true,
    "isActive": true
  },
  {
    "title": "Solar Net Metering Setup",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar6.png",
    "price": 7,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar engineer"],
    "tags": ["net metering", "grid solar"],
    "rating": 0,
    "isMostBooked": true,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Off-Grid Solar System Installation",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar7.png",
    "price": 18,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar technician"],
    "tags": ["off grid", "solar backup"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "On-Grid Solar System Installation",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar8.png",
    "price": 16,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar technician"],
    "tags": ["on grid", "net meter"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },

  { "title": "Hybrid Solar System Installation", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar9.png", "price": 20, "serviceType": "Solar", "category": "Electrical", "specialization": ["solar engineer"], "tags": ["hybrid solar"], "rating": 0, "isMostBooked": false, "isTopCategory": false, "isNewLaunched": true, "isActive": true },
  { "title": "Solar System Repair", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar10.png", "price": 6, "serviceType": "Solar", "category": "Electrical", "specialization": ["solar technician"], "tags": ["repair", "solar service"], "rating": 0, "isMostBooked": true, "isTopCategory": false, "isNewLaunched": false, "isActive": true },
  { "title": "Solar Panel Replacement", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar11.png", "price": 9, "serviceType": "Solar", "category": "Electrical", "specialization": ["solar technician"], "tags": ["panel replace"], "rating": 0, "isMostBooked": false, "isTopCategory": false, "isNewLaunched": false, "isActive": true },
  { "title": "Solar Wiring & Cabling", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar12.png", "price": 6, "serviceType": "Solar", "category": "Electrical", "specialization": ["electrician"], "tags": ["dc wiring", "ac wiring"], "rating": 0, "isMostBooked": false, "isTopCategory": false, "isNewLaunched": false, "isActive": true },

  { "title": "Solar AMC Service", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar13.png", "price": 4, "serviceType": "Solar", "category": "Electrical", "specialization": ["solar technician"], "tags": ["amc", "maintenance"], "rating": 0, "isMostBooked": true, "isTopCategory": false, "isNewLaunched": false, "isActive": true },
  { "title": "Solar Energy Audit", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar14.png", "price": 6, "serviceType": "Solar", "category": "Electrical", "specialization": ["solar engineer"], "tags": ["audit", "energy efficiency"], "rating": 0, "isMostBooked": false, "isTopCategory": false, "isNewLaunched": false, "isActive": true },
  { "title": "Solar Pump Installation", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar15.png", "price": 14, "serviceType": "Solar", "category": "Electrical", "specialization": ["solar technician"], "tags": ["solar pump", "agriculture"], "rating": 0, "isMostBooked": false, "isTopCategory": false, "isNewLaunched": false, "isActive": true },
  { "title": "Solar Street Light Installation", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar16.png", "price": 7, "serviceType": "Solar", "category": "Electrical", "specialization": ["electrician"], "tags": ["street light", "solar light"], "rating": 0, "isMostBooked": false, "isTopCategory": false, "isNewLaunched": false, "isActive": true },

  { "title": "Solar EV Charger Setup", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar17.png", "price": 12, "serviceType": "Solar", "category": "Electrical", "specialization": ["solar engineer"], "tags": ["ev charger", "solar ev"], "rating": 0, "isMostBooked": true, "isTopCategory": false, "isNewLaunched": true, "isActive": true },
  { "title": "Solar Water Heater Installation", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar18.png", "price": 10, "serviceType": "Solar", "category": "Electrical", "specialization": ["solar technician"], "tags": ["water heater"], "rating": 0, "isMostBooked": false, "isTopCategory": false, "isNewLaunched": false, "isActive": true },

  { "title": "Solar System Load Calculation", "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar19.png", "price": 4, "serviceType": "Solar", "category": "Electrical", "specialization": ["solar engineer"], "tags": ["load", "calculation"], "rating": 0, "isMostBooked": false, "isTopCategory": false, "isNewLaunched": false, "isActive": true },
  
  {
    "title": "Solar Plant Monitoring System",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar20.png",
    "price": 6,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar engineer"],
    "tags": ["monitoring", "solar plant", "dashboard"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": true,
    "isActive": true
  },
  {
    "title": "Solar Panel Tilt & Angle Optimization",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar21.png",
    "price": 4,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar technician"],
    "tags": ["tilt", "angle", "efficiency"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar Lightning Protection System",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar22.png",
    "price": 7,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["electrician"],
    "tags": ["lightning", "protection", "safety"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar Earthing & Grounding",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar23.png",
    "price": 5,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["electrician"],
    "tags": ["earthing", "grounding"],
    "rating": 0,
    "isMostBooked": true,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar DCDB & ACDB Installation",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar24.png",
    "price": 6,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["electrician"],
    "tags": ["dcdb", "acdb", "distribution"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar Power Quality Testing",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar25.png",
    "price": 5,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar engineer"],
    "tags": ["testing", "power quality"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar Panel Thermal Inspection",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar26.png",
    "price": 7,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar engineer"],
    "tags": ["thermal", "inspection", "hotspots"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": true,
    "isActive": true
  },
  {
    "title": "Solar Performance Report Generation",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar27.png",
    "price": 3,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar engineer"],
    "tags": ["report", "performance"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": true,
    "isActive": true
  },
  {
    "title": "Solar Subsidy & Government Paperwork",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar28.png",
    "price": 4,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar consultant"],
    "tags": ["subsidy", "govt", "documents"],
    "rating": 0,
    "isMostBooked": true,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar Project Design & Consultancy",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar29.png",
    "price": 10,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar consultant", "solar engineer"],
    "tags": ["design", "consultancy"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": true,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar Farm Maintenance",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar30.png",
    "price": 22,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar technician"],
    "tags": ["solar farm", "maintenance"],
    "rating": 0,
    "isMostBooked": true,
    "isTopCategory": true,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar Tracker Installation",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar31.png",
    "price": 14,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar engineer"],
    "tags": ["solar tracker", "automation"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": true,
    "isActive": true
  },
  {
    "title": "Solar Remote Monitoring Setup",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar32.png",
    "price": 8,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar engineer"],
    "tags": ["remote", "monitoring"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": true,
    "isActive": true
  },
  {
    "title": "Solar Plant Commissioning",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar33.png",
    "price": 12,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar engineer"],
    "tags": ["commissioning", "testing"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": true,
    "isNewLaunched": false,
    "isActive": true
  },
  {
    "title": "Solar Asset Management",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar34.png",
    "price": 9,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar consultant"],
    "tags": ["asset", "management"],
    "rating": 0,
    "isMostBooked": false,
    "isTopCategory": false,
    "isNewLaunched": true,
    "isActive": true
  },
  {
    "title": "Solar System Health Check",
    "cardIcon": "https://res.cloudinary.com/athratech/image/upload/v1763971582/fast_response_service/solar35.png",
    "price": 4,
    "serviceType": "Solar",
    "category": "Electrical",
    "specialization": ["solar technician"],
    "tags": ["health check", "inspection"],
    "rating": 0,
    "isMostBooked": true,
    "isTopCategory": false,
    "isNewLaunched": false,
    "isActive": true
  }
  

];



module.exports = serviceCardData;
